### PR TITLE
Sanitize inputs and conditionally render links

### PR DESCRIPTION
**Pull request by claytron5000**
Closes issue #8 

This uses the dompurify library with tagged template syntax to sanitize Google Sheets inputs values. 

Testing
- Add a `script` tag or other XSS technique to a value on the Google Sheet.
- render page
Expected result, the rest of the page renders as expected, the one "corrupted" field does not render.

As a bonus this conditionally renders both the slideLinke, speakerLink and the pipe seperator between the two(it only shows up if both links are available).

### CODE REVIEW

**Comment by claytron5000** [comment]
NOTE: tagged template literals is not supported in IE. If we need to support older browsers we should look at a different technique.

**Comment by rick02840** [comment]
Hi @claytron5000 I am having trouble resolving merge conflicts in `redesign.html`, probably because Aubrey's work had so many changes to it.  But was this work really in` js/session.js` and maybe I can just ignore changes to `redesign.html`, or are there important changes in  `redesign.html` that you needed as part of this?

**Comment by rick02840** [comment]
I think I got it -- copied `js/sessions.js` from this branch to the master branch and added this to `<head>` of `redesign.html` and `index.html`: 

`<script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/2.0.3/purify.min.js"></script>`

Seems to work on local, let me know if sounds incorrect.  I have not pushed it up yet.

**Comment by rick02840** [comment]
@claytron5000  OK I think I got this merged into master OK and I pushed it up.   Let me know if any issues.  Thanks!

**Pull request closed without merging**
